version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.2-node-browsers
    branches:
      only:
        - master
        - develop
    steps:
      - add_ssh_keys:
          fingerprints:
            - "e1:e9:00:a0:fc:99:cc:2e:1f:ac:0e:9e:46:4f:56:ba"
      - checkout
      - run: sudo apt-get update && sudo apt-get install lftp && sudo composer self-update
      - restore_cache:
          key: composer-cache-{{checksum "composer.lock"}}
      - run:
          name: PHP Dependencies
          command: composer install
      - save_cache:
          paths:
            - ./vendor
            - ~/.composer/cache
          key: composer-cache-{{checksum "composer.lock"}}
      - restore_cache:
          key: yarn-cache-{{checksum "./web/app/themes/tahosalodge/yarn.lock"}}
      - run:
          name: JS Dependencies
          command: cd ./web/app/themes/tahosalodge/ && yarn
      - save_cache:
          paths:
            - ./web/app/themes/tahosalodge/node_modules
          key: yarn-cache-{{checksum "./web/app/themes/tahosalodge/yarn.lock"}}
      - run:
          name: Build JS
          command: cd ./web/app/themes/tahosalodge/ && yarn prod
      - run:
          name: Deploy
          command: ~/project/scripts/deploy.sh
